name:  scribe_github_workflow

on: 
  push
  
jobs:
  scribe-report-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:

    

    - name: Generate cyclonedx json SBOM
      id: valiant_bom
      uses: scribe-security/action-bom@master
      with:
        type: git
        target: 'https://github.com/AkashPandey76/directus.git'
        format: json
        scribe-enable: true
        scribe-client-id: ${{ secrets.clientid }}
        scribe-client-secret: ${{ secrets.clientsecret }}
        product-key: Directus
